services:
  user_dashboard:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/user_dashboard"
      - "/opt/user_dashboard/node_modules"
    environment:
      - NEXT_WEBPACK_USEPOLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true